jobs:
  - name: runsh-job-pubparam
    type: runSh
    allowPublicAccess: false
    steps:
      - IN: sample-pubparam
      - TASK:
        - script: IN/sample-pub/gitRepo/echo.sh
    flags: job1param
    
  - name: runcliscript-job-pubparam
    type: runCLI
    allowPublicAccess: true
    steps:      
      - IN: sample-scriptpvtparam
      - TASK:
        - script: IN/sample-scriptpvt/gitRepo/echo.sh
    flags: job-runcliparam
        
        
  - name: manifest_dep_pubparam
    type: manifest
    allowPublicAccess: true
    steps:
      - IN: sample_img_pubparam
    flags: manifestparam

  - name: sample_publicrepo_runCI
    type: runCI
    allowPublicAccess: true
    steps:
      - IN: sample_publicrepo_ciRepo
    flags:
      - sample_publicrepo_runCIparam
      - sample_publicrepo_runCIEnabledFromCIbutAddedFlagsInJobsYmlparam
      
      
  - name: sample-release-pubparam
    type: release
    allowPublicAccess: true
    steps:
      - IN: sample-version-pubparam
      - TASK: managed
        bump: rc

  - name: runsh-param1-pub
    type: runSh
    steps:
      - IN: test_params1pub
      - TASK:
        - script: echo "A=$A"
        - script: echo "B=$B"
        - script: echo "p1=$p1"
        - script: echo "p2=$p2"