triggers:
  - name: tr1
    type: trigger
    version:
      counter: 5
      
  - name: tr2
    type: trigger
    version:
      counter: 2
      
  - name: tr3
    type: trigger
    version:
      counter: 5
      
  - name: tr4
    type: trigger
    version:
      counter: 0
      
  - name: tr5
    type: trigger
    version:
      counter: 6
      
  - name: tr6
    type: trigger
    version:
      counter: 0

  - name: tr7
    type: trigger
    version:
      counter: 0
      
  - name: tr8
    type: trigger
    version:
      counter: 0

  - name: tr9
    type: trigger
    version:
      counter: 0
  
  - name: tr10
    type: trigger
    version:
      counter: 0
  
  - name: tr11
    type: trigger
    version:
      counter: 0